

version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
permissions:
  - object: /
    pattern: "**"
    owner: centos
    group: centos
hooks:
  BeforeInstall:
    - location: /before_start.sh
      timeout: 300
      runas: centos
  AfterInstall:
    - location: /after_start.sh
      timeout: 300
      runas: centos