

version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: /home/centos/before_start.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /home/centos/after_start.sh
      timeout: 300
      runas: root