

version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
permissions:
  - object: /
    pattern: "**"
    owner: centos
    group: centos
hooks:
  BeforeInstall:
    - location: /BeforeInstall.sh
      timeout: 300
      runas: centos
  AfterInstall:
    - location: /AfterInstall.sh
      timeout: 300
      runas: centos